
### **1단계 :  CSV 파일 업로드**

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('.\data\지하수기초조사 데이터\지하수기초조사_수리상수DB.csv')
df.head(2)

C:\Users\user\AppData\Local\Temp\ipykernel_4260\821519715.py:1: DtypeWarning: Columns (17,22,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('.\data\지하수기초조사 데이터\지하수기초조사_수리상수DB.csv')

,시도,시군구,읍면동,리,번지,시도CODE,시군구CODE,MW_NAME,SW_NAME,SW_CODE,수문지질,수문지질_상세,TM_X_5186,TM_Y_5186,공번호,대수층,단공_다공,관정심도_m,관정구경_m,토출관직경,설치심도_m,양수능력_m,취수계획량,평균양수량,자연수위_m,안정수위_m,비양수량_t,K_m_day,T_m2_day,저류계수,참고문헌,출처,분류,상세
0,대전광역시,대덕구,덕암동,NaN,NaN,25,3023000000,대청댐,대청댐조정지,300805.0,"관입화성암(트라이아스기, 쥐라기)",e-2,238087.451205,424768.227081,BDDD 12,알수없음,NaN,50+,NaN,NaN,NaN,NaN,NaN,158.0,1.40,39.91,NaN,NaN,1.000000,NaN,대전지역 지하수 기초조사 보고서,기초조사,기존공양수시험,기존공양수시험
1,대전광역시,대덕구,신탄진동,NaN,NaN,25,3023000000,대청댐,대청댐,300804.0,변성암,h-2,241004.105339,424056.429748,BDDD 25,알수없음,NaN,50+,NaN,NaN,NaN,NaN,NaN,165.8,1.11,26.00,NaN,NaN,1.072381,NaN,대전지역 지하수 기초조사 보고서,기초조사,기존공양수시험,기존공양수시험

In [4]:
print(df.columns.tolist())

['시도', '시군구', '읍면동', '리', '번지', '시도CODE', '시군구CODE', 'MW_NAME', 'SW_NAME', 'SW_CODE', '수문지질', '수문지질_상세', 'TM_X_5186', 'TM_Y_5186', '공번호', '대수층', '단공_다공', '관정심도_m', '관정구경_m', '토출관직경', '설치심도_m', '양수능력_m', '취수계획량', '평균양수량', '자연수위_m', '안정수위_m', '비양수량_t', 'K_m_day', 'T_m2_day', '저류계수', '참고문헌', '출처', '분류', '상세']

In [5]:
ddf = pd.read_csv('.\data\지하수기초조사 데이터\지하수기초조사_수질DB.csv')
ddf.head(2)

C:\Users\user\AppData\Local\Temp\ipykernel_4260\4012919923.py:1: DtypeWarning: Columns (1,15,18,19,20,38,44,52,54,80,94,111,126) have mixed types. Specify dtype option on import or set low_memory=False.
  ddf = pd.read_csv('.\data\지하수기초조사 데이터\지하수기초조사_수질DB.csv')

,구분,연도,시도,시군구,읍면동,리,번지,MW_NAME,SW_NAME,수문지질,수문지질_상세,TM_X_5186,TM_X_5186.1,공번호,조사횟수,조사차수,조사시기,대수층,표고,관정심도,관정구경,Temp,pH,EC,DO,TDS,Ca,Mg,Na,K,HCO3,Cl,SO4,NO3,F,Fe,Mn,Si,CO3,SiO2,NH4_N,NH4,NO3_N,유기인,일반세균,일반세균_저온,일반세균_중온,수소이온농도_pH,용존산소량_DO,화학적산소요구량_COD,비소_As,세레늄_Se,알루미늄_Al,페니트로티온,맛,수은_Hg,카드뮴_Cd,파라티온_Parathion,디클로로메탄_Dichlomethans,구리_Cu,망간_Mn,카바릴_Carbaryl,말라티온_Malathion,암모니아성질소_NH3_N,납_Pb,불소_F,톨루엔_Toluene,에틸벤젠_Ethylbenzene,총트리할로메탄_THM,철_Fe,시안_CN,크실렌_Xylene,증발잔류물_R.E,디클로로에틸렌_Dichloroethylene,색도_Color,페놀_Phenol,6가크롬_Cr+6,질산성질소_NO3_N,질산염,트리클로로에탄_1_1_1_TCE,냄새,세제_ABS,황산이온_SO4_2,다이아지논_Diazion,트리클로로에틸렌_TCE,아연_Zn,탁도,염소이온_Cl_,사염화탄소,과망간산칼륨소비량,경도,벤젠_Benzene,대장균군,테트라클로로에틸렌,분원성연쇄상구균,녹농균,아황산환원혐기성포자형성균,살모넬라,쉬겔라,여시니아,보론,1_2_디브로모_3_클로로프로판,유리잔류염소,클로로포름,리튬,스트론튬,바륨,니켈,코발트,총용존성고형물질,인산염인,분원성대장균군,TBAC,DBRO,아질산이온,브롬,이산화질소,티타늄,바나듐,갈륨,저마늄,몰리브덴,세슘,라듐,토륨,톨륨,총대장균군,1_4_다이옥산,크롬
0,대구지역,2004,대구광역시,북구,국우동,-,661,금호강,팔거천,쇄설성 퇴적암,f,342635.140763,374099.534056,BGD0034,일회,-,2004년 04월,충적,-,3.1,-,15.2,6.87,468.0,4.58,233.0,35.47,13.73,27.17,10.80,107.96,33.760,30.37,42.00,NaN,0.09,NaN,NaN,0.04,NaN,NaN,NaN,9.487800,NaN,201.0,NaN,NaN,6.6,NaN,NaN,NaN,NaN,NaN,NaN,무미,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.264,NaN,NaN,NaN,0.09,NaN,NaN,333.0,NaN,2.0,NaN,NaN,9.4,NaN,NaN,무취,NaN,30.37,NaN,NaN,0.012,0.19,33.760,NaN,1.2,178.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,대구지역,2004,대구광역시,북구,국우동,-,382,금호강,팔거천,쇄설성 퇴적암,f,343423.415901,373340.270370,BGD0037,일회,-,2004년 04월,충적,-,4.7,-,12.3,7.20,338.0,3.77,167.0,27.89,12.42,15.50,2.51,92.88,17.255,25.79,13.58,NaN,0.08,NaN,NaN,0.11,NaN,NaN,NaN,3.067722,NaN,540.0,NaN,NaN,7.1,NaN,NaN,NaN,NaN,NaN,NaN,유미,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.01,NaN,0.217,NaN,NaN,NaN,0.08,NaN,NaN,195.0,NaN,1.0,NaN,NaN,3.0,NaN,NaN,유취,NaN,25.79,NaN,NaN,NaN,1.51,17.255,NaN,2.1,138.0,NaN,검출,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,검출,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print(ddf.columns.tolist())

['구분', '연도', '시도', '시군구', '읍면동', '리', '번지', 'MW_NAME', 'SW_NAME', '수문지질', '수문지질_상세', 'TM_X_5186', 'TM_X_5186.1', '공번호', '조사횟수', '조사차수', '조사시기', '대수층', '표고', '관정심도', '관정구경', 'Temp', 'pH', 'EC', 'DO', 'TDS', 'Ca', 'Mg', 'Na', 'K', 'HCO3', 'Cl', 'SO4', 'NO3', 'F', 'Fe', 'Mn', 'Si', 'CO3', 'SiO2', 'NH4_N', 'NH4', 'NO3_N', '유기인', '일반세균', '일반세균_저온', '일반세균_중온', '수소이온농도_pH', '용존산소량_DO', '화학적산소요구량_COD', '비소_As', '세레늄_Se', '알루미늄_Al', '페니트로티온', '맛', '수은_Hg', '카드뮴_Cd', '파라티온_Parathion', '디클로로메탄_Dichlomethans', '구리_Cu', '망간_Mn', '카바릴_Carbaryl', '말라티온_Malathion', '암모니아성질소_NH3_N', '납_Pb', '불소_F', '톨루엔_Toluene', '에틸벤젠_Ethylbenzene', '총트리할로메탄_THM', '철_Fe', '시안_CN', '크실렌_Xylene', '증발잔류물_R.E', '디클로로에틸렌_Dichloroethylene', '색도_Color', '페놀_Phenol', '6가크롬_Cr+6', '질산성질소_NO3_N', '질산염', '트리클로로에탄_1_1_1_TCE', '냄새', '세제_ABS', '황산이온_SO4_2', '다이아지논_Diazion', '트리클로로에틸렌_TCE', '아연_Zn', '탁도', '염소이온_Cl_', '사염화탄소', '과망간산칼륨소비량', '경도', '벤젠_Benzene', '대장균군', '테트라클로로에틸렌', '분원성연쇄상구균', '녹농균', '아황산환원혐기성포자형성균', '살모넬라', '쉬겔라', '여시니아', '보론', '1_2_디브로모_3_클로로프로판', '유리잔류염소', '클로로포름', '리튬', '스트론튬', '바륨', '니켈', '코발트', '총용존성고형물질', '인산염인', '분원성대장균군', 'TBAC', 'DBRO', '아질산이온', '브롬', '이산화질소', '티타늄', '바나듐', '갈륨', '저마늄', '몰리브덴', '세슘', '라듐', '토륨', '톨륨', '총대장균군', '1_4_다이옥산', '크롬']


### **2단계 :  데이터 처리 및 통합 (Core Dataset 생성)**

In [7]:
import pandas as pd

# --- 데이터 처리 로직 시작 ---

# 1. 필요한 컬럼만 선택
# 수질 데이터에서 필요한 컬럼 목록
cols_quality = [
    '공번호',
    '조사시기',
    # --- 질소/인 화합물 (영양염류) ---
    'NH4_N',
    '암모니아성질소_NH3_N',
    '유기인',
    '인산염인',
    '아질산이온',
    '질산염',

    # --- 중금속 및 금속류 ---
    '비소_As',
    '수은_Hg',
    '카드뮴_Cd',
    '납_Pb',
    '6가크롬_Cr+6',
    '크롬',
    '구리_Cu',
    '아연_Zn',
    '망간_Mn',
    '철_Fe',
    '알루미늄_Al',
    '세레늄_Se',
    '니켈',
    '바륨',

    # --- 휘발성 유기화합물(VOCs) 및 유기물질 ---
    '벤젠_Benzene',
    '톨루엔_Toluene',
    '에틸벤젠_Ethylbenzene',
    '크실렌_Xylene',
    '페놀_Phenol',
    '트리클로로에틸렌_TCE',
    '테트라클로로에틸렌',
    '사염화탄소',
    '디클로로메탄_Dichlomethans',
    '총트리할로메탄_THM',
    '1_4_다이옥산',

    # --- 농약류 ---
    # '유기인'은 중복되므로 한 번만 포함
    '페니트로티온',
    '파라티온_Parathion',
    '카바릴_Carbaryl',
    '말라티온_Malathion',
    '다이아지논_Diazion',

    # --- 미생물 ---
    '일반세균',
    '일반세균_저온',
    '일반세균_중온',
    '총대장균군',
    '대장균군',
    '분원성대장균군',
    '녹농균',
    '살모넬라',

    # --- 기타 이온 및 일반 오염 지표 ---
    '시안_CN',
    '불소_F',
    '염소이온_Cl_',
    '황산이온_SO4_2',
    '세제_ABS',
    '화학적산소요구량_COD',
]

# 수리상수 데이터에서 필요한 컬럼 목록
cols_hydro = [
    '공번호',
    '시도CODE',
    '시군구CODE',
    'K_m_day',     # 수리전도도
    'T_m2_day',    # 투수량계수
    '저류계수',

    'TM_X_5186',   # X좌표
    'TM_Y_5186'    # Y좌표
]

# 컬럼 목록을 기반으로 데이터프레임 필터링
df_quality_selected = ddf[cols_quality]
df_hydro_selected = df[cols_hydro]

# 수리상수 데이터는 '공번호' 기준으로 중복된 행이 있을 수 있으므로, 최신 데이터만 남기기 위해 중복을 제거합니다.
df_hydro_unique = df_hydro_selected.drop_duplicates(subset=['공번호'], keep='last').reset_index(drop=True)
print(f"  - 수리상수 데이터 중복 제거 완료: {len(df_hydro_selected)} -> {len(df_hydro_unique)}")

# 2. '공번호'를 Key로 사용하여 두 데이터프레임 병합
print("\n2. '공번호'를 기준으로 두 데이터를 병합합니다 (pd.merge)...")
# 수질 데이터(df_quality_selected)는 시계열이므로 그대로 두고,
# 관측정별로 고유한 값을 가지는 수리상수 데이터(df_hydro_unique)를 병합합니다.
# how='inner'는 양쪽 데이터에 모두 '공번호'가 존재하는 경우만 남깁니다.
gims_master_data = pd.merge(df_quality_selected, df_hydro_unique, on='공번호', how='inner')

# 3. 결과 확인 및 저장
print("\n3. 최종 통합 데이터 'gims_master_data.csv'를 생성합니다...")
# 최종 결과물의 상위 5개 행 출력
print("\n[병합 결과 미리보기 (상위 5개)]")
print(gims_master_data.head())

# 최종 결과물의 정보 요약 출력
print("\n[최종 데이터 정보]")
gims_master_data.info()

# 코랩 환경에 CSV 파일로 저장
# encoding='utf-8-sig'는 Excel에서 한글이 깨지지 않게 하기 위함입니다.
output_filename = './data/gims_master_data.csv'
gims_master_data.to_csv(output_filename, index=False, encoding='utf-8-sig')

print(f"\n작업 완료! '{output_filename}' 파일이 현재 디렉토리에 저장되었습니다.")

  - 수리상수 데이터 중복 제거 완료: 23141 -> 20450

2. '공번호'를 기준으로 두 데이터를 병합합니다 (pd.merge)...

3. 최종 통합 데이터 'gims_master_data.csv'를 생성합니다...

[병합 결과 미리보기 (상위 5개)]
       공번호       조사시기  NH4_N  암모니아성질소_NH3_N  유기인  인산염인  아질산이온  질산염  비소_As  \
0    BGE02  2004년 04월    NaN           0.01  NaN   NaN    NaN  NaN    NaN
1    DGE02  2004년 04월    NaN           0.02  NaN   NaN    NaN  NaN  0.017
2  DSD1335  2004년 04월    NaN            NaN  NaN   NaN    NaN  NaN    NaN
3  DSD2262  2004년 04월    NaN           0.07  NaN   NaN    NaN  NaN    NaN
4    DSE02  2004년 04월    NaN            NaN  NaN   NaN    NaN  NaN    NaN

   수은_Hg  카드뮴_Cd  납_Pb  6가크롬_Cr+6  크롬  구리_Cu   아연_Zn  망간_Mn  철_Fe 알루미늄_Al  \
0    NaN     NaN   NaN        NaN NaN    NaN   7.466  3.857  0.17     NaN
1    NaN     NaN   NaN        NaN NaN    NaN   0.412    NaN   NaN     NaN
2    NaN     NaN   NaN        NaN NaN    NaN   0.070    NaN   NaN     NaN
3    NaN     NaN   NaN        NaN NaN    NaN   0.006    NaN  0.22     NaN
4    NaN     NaN   NaN        NaN NaN    NaN  20.486  8.800  0.17     NaN

   세레늄_Se  니켈  바륨  벤젠_Benzene  톨루엔_Toluene  에틸벤젠_Ethylbenzene  크실렌_Xylene  \
0     NaN NaN NaN         NaN          NaN                NaN         NaN
1     NaN NaN NaN         NaN          NaN                NaN         NaN
2     NaN NaN NaN         NaN          NaN                NaN         NaN
3   0.008 NaN NaN         NaN          NaN                NaN         NaN
4   0.006 NaN NaN         NaN          NaN                NaN         NaN

   페놀_Phenol  트리클로로에틸렌_TCE  테트라클로로에틸렌  사염화탄소  디클로로메탄_Dichlomethans  \
0        NaN           NaN        NaN    NaN                   NaN
1        NaN           NaN        NaN    NaN                   NaN
2        NaN           NaN        NaN    NaN                   NaN
3        NaN           NaN        NaN    NaN                   NaN
4        NaN           NaN        NaN    NaN                   NaN

   총트리할로메탄_THM  1_4_다이옥산  페니트로티온  파라티온_Parathion  카바릴_Carbaryl  \
0          NaN       NaN     NaN             NaN           NaN
1          NaN       NaN     NaN             NaN           NaN
2          NaN       NaN     NaN             NaN           NaN
3          NaN       NaN     NaN             NaN           NaN
4          NaN       NaN     NaN             NaN           NaN

   말라티온_Malathion  다이아지논_Diazion    일반세균  일반세균_저온  일반세균_중온 총대장균군 대장균군 분원성대장균군  \
0             NaN            NaN  1010.0      NaN      NaN   NaN  NaN     NaN
1             NaN            NaN  2800.0      NaN      NaN   NaN  NaN     NaN
2             NaN            NaN   108.0      NaN      NaN   NaN   검출      검출
3             NaN            NaN   108.0      NaN      NaN   NaN   검출      검출
4             NaN            NaN  1050.0      NaN      NaN   NaN   검출      검출

   녹농균  살모넬라  시안_CN   불소_F  염소이온_Cl_  황산이온_SO4_2  세제_ABS  화학적산소요구량_COD  \
0  NaN   NaN    NaN  0.251     8.389       6.826     NaN           NaN
1  NaN   NaN    NaN  2.475    21.395      18.555     NaN           NaN
2  NaN   NaN    NaN  0.296    27.110      22.700     NaN           NaN
3  NaN   NaN    NaN  0.203    53.520      36.190     NaN           NaN
4  NaN   NaN    NaN  0.504    34.090      18.560     NaN           NaN

   시도CODE     시군구CODE      K_m_day   T_m2_day    저류계수      TM_X_5186  \
0      22  2723000000  0.993866188  10.016287  0.2250  346267.494203
1      22  2714000000  0.221661905  21.465312  0.0002  354773.913048
2      22  2771000000  0.624627617   2.248110  0.2160  322776.450782
3      22  2771000000  0.162467843   0.834985  0.0100  327184.385162
4      22  2771000000  0.225727712   3.142722  0.1680  332426.511657

       TM_Y_5186
0  370720.280443
1  368732.091530
2  344341.699674
3  363458.434700
4  365131.040164

[최종 데이터 정보]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2651 entries, 0 to 2650
Data columns (total 59 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   공번호                   2651 non-null   object
 1   조사시기                  2651 non-null   object
 2   NH4_N                 8 non-null      float64
 3   암모니아성질소_NH3_N         1988 non-null   float64
 4   유기인                   42 non-null     float64
 5   인산염인                  1103 non-null   float64
 6   아질산이온                 1095 non-null   float64
 7   질산염                   1226 non-null   float64
 8   비소_As                 1925 non-null   float64
 9   수은_Hg                 1767 non-null   float64
 10  카드뮴_Cd                1759 non-null   float64
 11  납_Pb                  1790 non-null   float64
 12  6가크롬_Cr+6             1369 non-null   float64
 13  크롬                    453 non-null    float64
 14  구리_Cu                 104 non-null    float64
 15  아연_Zn                 1661 non-null   float64
 16  망간_Mn                 1625 non-null   float64
 17  철_Fe                  1573 non-null   float64
 18  알루미늄_Al               1528 non-null   object
 19  세레늄_Se                1512 non-null   float64
 20  니켈                    24 non-null     float64
 21  바륨                    45 non-null     float64
 22  벤젠_Benzene            1840 non-null   float64
 23  톨루엔_Toluene           1854 non-null   float64
 24  에틸벤젠_Ethylbenzene     1829 non-null   float64
 25  크실렌_Xylene            1847 non-null   float64
 26  페놀_Phenol             1838 non-null   float64
 27  트리클로로에틸렌_TCE          1823 non-null   float64
 28  테트라클로로에틸렌             1841 non-null   float64
 29  사염화탄소                 1823 non-null   float64
 30  디클로로메탄_Dichlomethans  1821 non-null   float64
 31  총트리할로메탄_THM           282 non-null    float64
 32  1_4_다이옥산              4 non-null      float64
 33  페니트로티온                1744 non-null   float64
 34  파라티온_Parathion        1779 non-null   float64
 35  카바릴_Carbaryl          1543 non-null   float64
 36  말라티온_Malathion        8 non-null      float64
 37  다이아지논_Diazion         1768 non-null   float64
 38  일반세균                  203 non-null    object
 39  일반세균_저온               0 non-null      float64
 40  일반세균_중온               2 non-null      float64
 41  총대장균군                 776 non-null    object
 42  대장균군                  1032 non-null   object
 43  분원성대장균군               96 non-null     object
 44  녹농균                   0 non-null      float64
 45  살모넬라                  0 non-null      float64
 46  시안_CN                 1810 non-null   float64
 47  불소_F                  1643 non-null   float64
 48  염소이온_Cl_              1621 non-null   float64
 49  황산이온_SO4_2            1672 non-null   float64
 50  세제_ABS                50 non-null     float64
 51  화학적산소요구량_COD          37 non-null     float64
 52  시도CODE                2651 non-null   int64
 53  시군구CODE               2651 non-null   int64
 54  K_m_day               1995 non-null   object
 55  T_m2_day              2644 non-null   float64
 56  저류계수                  275 non-null    float64
 57  TM_X_5186             2651 non-null   float64
 58  TM_Y_5186             2651 non-null   float64
dtypes: float64(49), int64(2), object(8)
memory usage: 1.2+ MB

작업 완료! './data/gims_master_data.csv' 파일이 현재 디렉토리에 저장되었습니다.

### GIMS 데이터 시군구CODE - 시군구명(법정동코드) 맵핑

In [8]:


# 2. pandas import 및 경로 설정
import pandas as pd

# 파일 경로
gims_path = './data/gims_master_data.csv'
lawcode_path = './data/법정동시군구/법정동코드 전체자료.csv'

# 3. 파일 불러오기
df_gims = pd.read_csv(gims_path)
df_law = pd.read_csv(lawcode_path, encoding='utf-8-sig')

# 4. GIMS 코드 전처리: 문자열로 변환 후 앞 10자리 추출
df_gims['시군구코드_10자리'] = df_gims['시군구CODE'].astype(str).str[:10]

# 5. 병합을 위한 컬럼 이름 통일
df_law = df_law.rename(columns={'법정동코드': '시군구코드_10자리', '법정동명': '시군구명'})
df_law['시군구코드_10자리'] = df_law['시군구코드_10자리'].astype(str)

# 6. 병합 수행 (left join)
df_merged = df_gims.merge(df_law[['시군구코드_10자리', '시군구명']], on='시군구코드_10자리', how='left')

# 7. 결과 확인
print("✅병합 완료! 병합된 데이터 예시:")
print(df_merged[['시군구CODE', '시군구명']].head())

# 8. 저장 경로 및 저장
save_path = './data/gims_master_data2.csv'
df_merged.to_csv(save_path, index=False, encoding='utf-8-sig')

print(" 저장 완료! 경로:")
print(save_path)

✅병합 완료! 병합된 데이터 예시:
      시군구CODE       시군구명
0  2723000000   대구광역시 북구
1  2714000000   대구광역시 동구
2  2771000000  대구광역시 달성군
3  2771000000  대구광역시 달성군
4  2771000000  대구광역시 달성군
 저장 완료! 경로:
./data/gims_master_data2.csv